### ISSUE TITLE
Nie działa tworzenie konta

### ISSUE THREAD

**Issue by lo1cgsan** [izielin/bookshop#2]
Podczas próby utworzenia konta dostaję błąd: SMTPAuthenticationError at /signup/
![Zrzut ekranu z 2020-04-10 11-33-52](https://user-images.githubusercontent.com/12935422/78981235-c951b800-7b1f-11ea-9efa-4a531be3a2e8.png)

**Comment by izielin** [comment]
błąd najprawdopodobniej wynika z niezaznaczenia jednej opcji w koncie gmail, mianowicie możliwość logowania z innych urządzeń, nie miałem możliwości testowania rejestracji na innym urządzeniu więc przeoczyłem ten błąd, wydaje mi się, że jest już naprawiony, prosiłbym o sprawdzenie i w razie błędów o kontakt

**Comment by izielin** [comment]
spróbowałem odpalić projekt na innym laptopie i się zarejestrować, nie pojawia się żaden błąd, email zostaje wysłany a użytkownik utworzony
